### PR TITLE
Ruby 1.8 compatible refactoring

### PR DESCRIPTION
**Pull request by kopischke**
Makes the workflow fully compatible with the system Ruby on OS X below 10.9 by
- removing _rb-appscript_ dependency as it segfaults on OS X 10.8.5
- switching to _active-support_ 3.2.x as version 4 is not supported for Ruby versions below < 1.9
- using _uuid-tools_ to generate UUIDs as _securerandom_ does not support this for Ruby versions below < 1.9
- reworking the bundled gem folder structure and loader to allow for Ruby versions specific loading (which prohibits direct inclusion of vendored Bundler dirs [contact me for a ZIP of the current structure])

It also addresses a number of issues I have found while testing the above, principally concerning empty and / or invalid last.fm data being returned and feedback about iTunes song retrieval, as well as performing basic localization (for numbers and dates only for now) and doing minor code cleanup. 

**Unluckily, this cannot be easily merged with the current master’s branch HEAD, as some of your refactoring breaks the above (notably, the switch to Ruby’s 1.9 hash declaration syntax in b4c4306e5629dd54040e265add7dca61a5ba4979 and 72d2fcddca54fc9292ef30599574367756266d2b).** If you want to pull, I suggest branching from fdc58fe9a32ef91e5174831759d155b8b1e20031 and merging/rebasing on that, then cherry picking your master commits.

### CODE REVIEW

**Comment by filipebarros** [comment]
I pushed your commits into a new branch, and I'll be adding some of your code (if you don't mind) into the version I'm working. Can you send me the zip of the bundler (or the whole alfredworkflow file) so I can add it to the repo? I'm going to reference you in the README file as the developer of the ruby1.8 version of the workflow.

**Comment by kopischke** [comment]
Yeah, of course, pick and use whatever you feel suits you, that’s the beauty of OSS :). Technically, this version is not _the_ 1.8 version, as it runs fine on Ruby 2 (which takes precedence over 1.8.7 on my system, and thus I as thoroughly tested as 1.8; I don’t have 1.9 installed to test, but in my experience, anything that runs on 1.8.7 and 2.0.0 runs on 1.9.x too). The workflow is available as part of [the v1.1.0 release](https://github.com/kopischke/alfredfm/releases/tag/v1.1.0).

**Comment by kopischke** [comment]
BTW, I have some tentative refactoring underway, but this would diverge even more from your master branch. Would you be interested in merging my fork into `master` and coordinate refactoring (no biggie if you don’t – it’s your workflow, after all)?

**Comment by filipebarros** [comment]
Of course, I'll resolve the conflicts and merge it

**Comment by kopischke** [comment]
Yeah, sorry to offload this to you, but that should be **much** easier than me trying to rebase on current `master`. Shoot me an email if you feel like discussing refactoring (my address is on my profile).

**Comment by filipebarros** [comment]
I merged and it seemed ok (I just corrected 2 typos you had in 2 files). I'll try to do some changes during the weekend (remove similar files that can be joined in just one, etc...)

**Pull request merged**
